### PR TITLE
Allow pickling again

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
This should allow pickling again for the core python and cython code, issue #3. To simplify things also the compare operator was added.

### CODE REVIEW

**Comment by grantjenks** [comment]
Unfortunately getstate/setstate didn't work locally. I changed it to use reduce. Pickling works at all protocol levels for Python/Cython version at 1.2.0 and later.

**Comment by FlorianWilhelm** [comment]
That's strange since the unit tests worked for all kinds of different Python versions. Do you know why?

**Comment by grantjenks** [comment]
All Python versions use protocol version 0 by default. Tests now try all supported pickle protocol levels on all Python versions.

**Comment by FlorianWilhelm** [comment]
Okay, thanks. Do you know if a ``namedtuple`` would also work? My use case is that I want to save the current state somewhere in a database. Of course I can just store that tuple but it could lead to confusion when reading in the state again. A change in the order will lead to a wrong state that goes unnoticed. Having a name for each state parameter would at least feel much more safe :-)

Two more things I noticed. I ran ``flake8`` on your code and there are some PEP8 problems regarding number of blank lines. Also I would name the function ``fromstate`` rather ``from_state`` since we also have ``set_state`` and ``get_state`` to be more consistent. 

That being said. Thanks a lot for your fast acceptance of change request and your overall cooperation. I think runstats is really helpful!

**Comment by grantjenks** [comment]
I considered namedtuple but it seemed kind of over-engineering. Personally I still much prefer pickle. My other qualm with exposing the internal names is that they are arbitrary. I just chose short Greek letters.

I don't worry too much about blank line messages from flake8. I like whitespace. I do run pylint though for bugs and best practices.

The spelling of fromstate is a toss-up. Consider dict.fromkeys as a counter example.

Plenty to still change to suit to taste but hopefully all the functionality you need is there. Could I quote you as a testimonial of the project? What would you like me to link to?

**Comment by FlorianWilhelm** [comment]
Agreed, the names are arbitrary but they provide an easier reference to a value then just an index. A matter of taste as you said.

Regarding the pep8 conformance, I still think that is a good practice to follow that but again a matter of taste and it's your project ;-)

You are right with the dict.fromkeys example but then again it's also ``__setstate__`` therefore it's consistent in the Python core libraries. On the contrary, in ``Statistics`` the method naming scheme is now inconsistent since we have ``set_state`` and ``fromstate``. One could of course also resolve this by renaming ``set_state``/``get_state`` to ``setstate``/``get_state``.

You can quote me of course and you can link either to my github profile page or to my [blog](http://www.florianwilhelm.info/).

**Pull request merged**
